#Generated by GPT to show margin

import matplotlib.pyplot as plt
import numpy as np

def plot_svm_margin(X, y, model):

    w = model.w_
    b = model.b_

    x_vals = np.linspace(X[:,0].min(), X[:,0].max(), 100)

    decision = (-w[0]*x_vals - b) / w[1]
    margin_up = (-w[0]*x_vals - b + 1) / w[1]
    margin_down = (-w[0]*x_vals - b - 1) / w[1]

    plt.scatter(X[:,0], X[:,1], c=y)

    plt.plot(x_vals, decision, label="Decision Boundary")
    plt.plot(x_vals, margin_up, linestyle='--', label="Margin +1")
    plt.plot(x_vals, margin_down, linestyle='--', label="Margin -1")

    plt.fill_between(x_vals, margin_down, margin_up, alpha=0.2)

    plt.legend()
    plt.title("SVM Margin Band")